variable "node_instance_type" {
  description = "Instance type to use for the XRd worker node instances"
  type        = string
  default     = "m5.2xlarge"
}

variable "node_ami" {
  description = <<-EOT
  AMI to use for the XRd worker node instances.
  If null, the latest AMI generated by XRd Packer for the relevant cluster version is used.
  EOT
  type        = string
  default     = null
}

variable "placement_group" {
  description = <<-EOT
  Placement group in which to start the XRd worker node instances.
  If null, the XRd worker node instances are started in the placement group created by the Bootstrap configuration.
  If set to the empty string "", the XRd worker node instances are not started in a placement group.
  EOT
  type        = string
  default     = null
}
