output "hugepages_gb" {
  description = <<-EOT
  The number of 1GiB hugepages allocated.
  This may be null if not using an XRd AMI generated by Packer.
  EOT
  value       = local.hugepages_gb
}

output "id" {
  description = "ID of the node"
  value       = aws_instance.this.id
}

output "instance_type" {
  description = "Instance type"
  value       = aws_instance.this.instance_type
}

output "isolated_cores" {
  description = <<-EOT
  The CPUs marked as isolated.
  This may be null if not using an XRd AMI generated by Packer.
  EOT
  value       = local.isolated_cores
}

output "isolated_cores_list" {
  description = <<-EOT
  The CPUs marked as isolated, as a list of numbers.
  This may be null if not using an XRd AMI generated by Packer.
  EOT
  value       = local.isolated_cores_list
}

output "private_ip" {
  description = "Primary private IPv4 address of the node"
  value       = aws_instance.this.private_ip
}

output "xrd_vr_cpuset" {
  description = <<-EOT
  If this node is intended for an XRd vRouter workload, this is the intended CPU set provided for XRd vRouter use.
  This may be null if not using an XRd AMI generated by Packer.
  EOT
  value       = local.xrd_vr_cpuset
}

output "xrd_vr_cp_num_cpus" {
  description = <<-EOT
  If this node is intended for an XRd vRouter workload, this is the intended number of control-plane CPUs.
  This may be null if not using an XRd AMI generated by Packer.
  EOT
  value       = local.xrd_vr_cp_num_cpus
}
