variable "node_ami" {
  description = <<-EOT
  AMI to use for the single worker node instance.
  If null, the latest AMI generated by XRd Packer for the relevant cluster version is used.
  EOT
  type        = string
  default     = null
}

variable "node_instance_type" {
  description = "Instance type to use for the single worker node instance"
  type        = string
  default     = "m5.2xlarge"

  validation {
    condition     = contains(["m5.2xlarge", "m5n.2xlarge", "m5.24xlarge", "m5n.24xlarge"], var.node_instance_type)
    error_message = "Allowed values are m5.2xlarge, m5n.2xlarge, m5.24xlarge, m5n.24xlarge"
  }
}
