name: pre-commit

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "gh-actions"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          cache: "pip"
      - uses: pre-commit/action@v3.0.0
