name: pre-commit

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "gh-actions"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup prerequisites"
        run: |
          curl https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz | sudo tar xz -C /usr/bin terraform-docs
      - uses: actions/setup-python@v3
        with:
          cache: "pip"
      - uses: pre-commit/action@v3.0.0
