---
name: pre-commit

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "^1.3.7"
            terraform_wrapper: false

      - name: "Setup prerequisites"
        # yamllint disable rule:line-length
        run: |
          curl -s -L https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz | tar xz -C /usr/local/bin terraform-docs
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        # yamllint enable rule:line-length

      - uses: actions/setup-python@v3
        with:
          cache: "pip"

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--hook-stage manual --all-files"
