name: tests

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "*.md"
  push:
    branches:
      - "gh-actions"
jobs:
  test:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: "actions/checkout@main"
        with:
          fetch-depth: 0

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - name: "Setup Python"
        uses: "actions/setup-python@master"
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install Python requirements"
        run: |
          pip install -U pip wheel
          pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest tests/
